server:
  port: 8080

spring:
  profiles:
    default: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
  jwt:
    secret: ${JWT_SECRET}

  cloud:
    aws:
      credentials:
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}
      s3:
        bucketName: ${S3_BUCKET_NAME}
      region:
        static: ap-northeast-2
      stack:
        auto: false

---
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: create
  jpa:
    hibernate:
      ddl-auto: create
---
server:
  port: 8083

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
---
fcm:
  firebase_config_path: firebase/firebase_service_key.json
  api_url: https://fcm.googleapis.com/v1/projects/timecalling-2025/messages:send
